public class WebUserWrapper {
    public String id;	//1
	public String name;	//Leanne Graham
	public String userName;	//Bret
	public String email;	//Sincere@april.biz
	public Address address;
	public String phone;	//1-770-736-8031 x56442
	public String website;	//hildegard.org
    
	public Company company;
    public class Address {
		public String street;	//Kulas Light
		public String suite;	//Apt. 556
		public String city;	//Gwenborough
		public String zipcode;	//92998-3874
		public Geo geo;
	}
	public class Geo {
		public String lat;	//-37.3159
		public String lng;	//81.1496
	}
	public class Company {
		public String name;	//Romaguera-Crona
		public String catchPhrase;	//Multi-layered client-server neural-net
		public String bs;	//harness real-time e-markets
	}
    
    
}